package com.bancodebogota.customers.arrangement.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2020-09-03T16:24:13.977-05:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "urn://bancodebogota.com/customers/arrangement/service/", name = "CustomerInformationNoveltyManagement")
@XmlSeeAlso({com.bancodebogota.customers.involvedparty.event.ObjectFactory.class, com.bancodebogota.ifx.base.v2.ObjectFactory.class, com.bancodebogota.ifx.base.v1.ObjectFactory.class, ObjectFactory.class, com.bancodebogota.customers.classification.v1.ObjectFactory.class, com.bancodebogota.ifx.base.v3.ObjectFactory.class, com.bancodebogota.ifx.lite.v1.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomerInformationNoveltyManagement {

    @WebMethod(action = "urn://bancodebogota.com/customers/arrangement/service/modCustNovelty")
    @WebResult(name = "modCustNoveltyResponse", targetNamespace = "urn://bancodebogota.com/customers/arrangement/service/", partName = "modCustNoveltyResult")
    public ModCustNoveltyResponse modCustNovelty(
        @WebParam(partName = "modCustNoveltyParameters", name = "modCustNoveltyRequest", targetNamespace = "urn://bancodebogota.com/customers/arrangement/service/")
        ModCustNoveltyRequest modCustNoveltyParameters
    ) throws ModCustNoveltyFaultMsg;
}
