package com.bancodebogota.customers.arrangement.service;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2020-09-03T16:24:13.994-05:00
 * Generated source version: 3.2.2
 *
 */
@WebServiceClient(name = "CustomerInformationNoveltyManagementSvc",
                  wsdlLocation = "classpath:wsdl/CustomerInformationNoveltyManagement.wsdl",
                  targetNamespace = "urn://bancodebogota.com/customers/arrangement/service/")
public class CustomerInformationNoveltyManagementSvc extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn://bancodebogota.com/customers/arrangement/service/", "CustomerInformationNoveltyManagementSvc");
    public final static QName CustomerInformationNoveltyManagementPort = new QName("urn://bancodebogota.com/customers/arrangement/service/", "CustomerInformationNoveltyManagementPort");
    static {
        URL url = CustomerInformationNoveltyManagementSvc.class.getClassLoader().getResource("wsdl/CustomerInformationNoveltyManagement.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(CustomerInformationNoveltyManagementSvc.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/CustomerInformationNoveltyManagement.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerInformationNoveltyManagementSvc(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerInformationNoveltyManagementSvc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerInformationNoveltyManagementSvc() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CustomerInformationNoveltyManagementSvc(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CustomerInformationNoveltyManagementSvc(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CustomerInformationNoveltyManagementSvc(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CustomerInformationNoveltyManagement
     */
    @WebEndpoint(name = "CustomerInformationNoveltyManagementPort")
    public CustomerInformationNoveltyManagement getCustomerInformationNoveltyManagementPort() {
        return super.getPort(CustomerInformationNoveltyManagementPort, CustomerInformationNoveltyManagement.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerInformationNoveltyManagement
     */
    @WebEndpoint(name = "CustomerInformationNoveltyManagementPort")
    public CustomerInformationNoveltyManagement getCustomerInformationNoveltyManagementPort(WebServiceFeature... features) {
        return super.getPort(CustomerInformationNoveltyManagementPort, CustomerInformationNoveltyManagement.class, features);
    }

}
