
package com.bancodebogota.customers.arrangement.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.2
 * 2020-09-03T16:24:13.914-05:00
 * Generated source version: 3.2.2
 */

@WebFault(name = "GeneralException", targetNamespace = "urn://bancodebogota.com/ifx/base/v1/")
public class ModCustNoveltyFaultMsg extends Exception {

    private com.bancodebogota.ifx.base.v1.GeneralExceptionType generalException;

    public ModCustNoveltyFaultMsg() {
        super();
    }

    public ModCustNoveltyFaultMsg(String message) {
        super(message);
    }

    public ModCustNoveltyFaultMsg(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ModCustNoveltyFaultMsg(String message, com.bancodebogota.ifx.base.v1.GeneralExceptionType generalException) {
        super(message);
        this.generalException = generalException;
    }

    public ModCustNoveltyFaultMsg(String message, com.bancodebogota.ifx.base.v1.GeneralExceptionType generalException, java.lang.Throwable cause) {
        super(message, cause);
        this.generalException = generalException;
    }

    public com.bancodebogota.ifx.base.v1.GeneralExceptionType getFaultInfo() {
        return this.generalException;
    }
}
